# coding: utf-8
import torch
import torch.nn as nn
import torch.nn.functional as F


class AntiPrototypeGenerator(nn.Module):
    def __init__(self, embed_dim, condition_dim, hidden_dim=128, gate_type='scalar', normalize_output=True):
        super().__init__()
        self.embed_dim = int(embed_dim)
        self.condition_dim = int(condition_dim)
        self.hidden_dim = int(hidden_dim)
        self.gate_type = str(gate_type).lower()
        self.normalize_output = bool(normalize_output)
        if self.gate_type not in ('scalar', 'vector'):
            raise ValueError(f'Unsupported gate_type: {self.gate_type}')

        gate_dim = 1 if self.gate_type == 'scalar' else self.embed_dim
        input_dim = self.embed_dim * 2 + self.condition_dim
        self.gate_mlp = nn.Sequential(
            nn.Linear(input_dim, self.hidden_dim),
            nn.SiLU(),
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.SiLU(),
            nn.Linear(self.hidden_dim, gate_dim),
        )

    def forward(self, x0, z_pos, cond, anti_eta):
        # x0: [B, D]
        # z_pos: [B, D]
        # cond: [B, C]
        # anti_eta: float
        gate_input = torch.cat([x0, z_pos, cond], dim=-1)  # [B, 2D + C]
        gate = torch.sigmoid(self.gate_mlp(gate_input))  # [B, 1] or [B, D]
        direction = z_pos - x0  # [B, D]
        z_neg = x0 - float(anti_eta) * gate * direction  # [B, D]
        # These negative prototypes are anti-prototypes induced from the reverse
        # direction of the learned positive transport, rather than generated by
        # independent negative flows.
        if self.normalize_output:
            z_neg = F.normalize(z_neg, dim=-1)
        return z_neg, gate


if __name__ == '__main__':
    torch.manual_seed(2026)

    batch_size = 4
    embed_dim = 12
    condition_dim = 20
    x0 = torch.randn(batch_size, embed_dim)
    z_pos = torch.randn(batch_size, embed_dim)
    cond = torch.randn(batch_size, condition_dim)

    scalar_model = AntiPrototypeGenerator(
        embed_dim=embed_dim,
        condition_dim=condition_dim,
        hidden_dim=16,
        gate_type='scalar',
        normalize_output=True,
    )
    vector_model = AntiPrototypeGenerator(
        embed_dim=embed_dim,
        condition_dim=condition_dim,
        hidden_dim=16,
        gate_type='vector',
        normalize_output=True,
    )

    z_neg_scalar, gate_scalar = scalar_model(x0, z_pos, cond, anti_eta=0.5)
    z_neg_vector, gate_vector = vector_model(x0, z_pos, cond, anti_eta=0.5)

    assert z_neg_scalar.shape == (batch_size, embed_dim)
    assert gate_scalar.shape == (batch_size, 1)
    assert z_neg_vector.shape == (batch_size, embed_dim)
    assert gate_vector.shape == (batch_size, embed_dim)
    print('AntiPrototypeGenerator smoke test passed.')
